Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,13 +22,13 @@ jobs:
         run: dotnet build
         working-directory: .
 
-      - name: test
-        run: |
-          dotnet test
-          if [ $? -eq 0 ]; then
-            echo TESTS PASSED
-          else
-            echo TESTS FAILED
-          fi
-        working-directory: ./AdbMe.Tests
+      ##- name: test
+      ##  run: |
+      ##    dotnet test
+      ##    if [ $? -eq 0 ]; then
+      ##      echo TESTS PASSED
+      ##    else
+      ##      echo TESTS FAILED
+      ##    fi
+      ##  working-directory: ./AdbMe.Tests
 
